### PR TITLE
Update for Elm 0.13

### PR DESCRIPTION
**Pull request by deadfoxygrandpa**
I wanted to use this library in a project and made these local changes. It would be nice to push them to the catalog.

### CODE REVIEW

**Comment by jcollard** [comment]
Awesome! Thanks.

**Comment by deadfoxygrandpa** [comment]
Cool, that was fast.

**Comment by deadfoxygrandpa** [comment]
Can you get this pushed to the Elm catalog?

**Comment by jcollard** [comment]
I don't have Elm 0.13 installed yet.

Before going through the install process, could you try checking this project out and running `elm-get publish`. I think you can publish others libraries (assuming it is on github).

**Comment by deadfoxygrandpa** [comment]
Can you tag this release 0.4 here on GitHub?

**Comment by jcollard** [comment]
Done.

**Comment by deadfoxygrandpa** [comment]
OK, I think it's worked. I didn't realize you could publish other people's libraries.

**Comment by deadfoxygrandpa** [comment]
Yep, I just verified it and it's working! Thanks for the quick responses.

**Comment by jcollard** [comment]
Awesome. I also believe you can `elm-get install` on non-published repositories. However, once they are published, you can only elm-get on tags that have been published.

**Pull request merged**
